version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3001:3001"
    env_file:
      - backend/.env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - nextstep-net

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - nextstep-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nextstep_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - nextstep-net

volumes:
  postgres_data:

networks:
  nextstep-net:
